<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="vprybeha-w10" ignored="0" name="ContactUS forms" tests="3" failures="3" timestamp="15 Feb 2019 19:16:06 GMT" time="26.36" errors="0">
  <testcase name="ContactUSForms_ContactUS" time="3.482" classname="UnitClassSet.ContactUS.test_ContactUS">
    <failure type="java.util.InputMismatchException">
      <![CDATA[java.util.InputMismatchException
at java.util.Scanner.throwFor(Scanner.java:864)
at java.util.Scanner.next(Scanner.java:1485)
at java.util.Scanner.nextInt(Scanner.java:2117)
at java.util.Scanner.nextInt(Scanner.java:2076)
at UnitClassSet.ContactUS.Raise_Funds_ContactUS_Form.SeriesOne_FillInContactUSForm(Raise_Funds_ContactUS_Form.java:34)
at UnitClassSet.ContactUS.test_ContactUS.ContactUSForms_ContactUS(test_ContactUS.java:21)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
... Removed 10 stack frames]]>
    </failure>
  </testcase> <!-- ContactUSForms_ContactUS -->
  <testcase name="ContactUSForms_License_Platform" time="5.091" classname="UnitClassSet.ContactUS.test_ContactUS">
    <failure type="java.util.InputMismatchException">
      <![CDATA[java.util.InputMismatchException
at java.util.Scanner.throwFor(Scanner.java:864)
at java.util.Scanner.next(Scanner.java:1485)
at java.util.Scanner.nextInt(Scanner.java:2117)
at java.util.Scanner.nextInt(Scanner.java:2076)
at UnitClassSet.ContactUS.Raise_Funds_ContactUS_Form.SeriesOne_FillInContactUSForm(Raise_Funds_ContactUS_Form.java:34)
at UnitClassSet.ContactUS.test_ContactUS.ContactUSForms_License_Platform(test_ContactUS.java:16)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
... Removed 10 stack frames]]>
    </failure>
  </testcase> <!-- ContactUSForms_License_Platform -->
  <testcase name="ContactUSForms_Raise_Funds" time="3.563" classname="UnitClassSet.ContactUS.test_ContactUS">
    <failure type="java.util.InputMismatchException">
      <![CDATA[java.util.InputMismatchException
at java.util.Scanner.throwFor(Scanner.java:864)
at java.util.Scanner.next(Scanner.java:1485)
at java.util.Scanner.nextInt(Scanner.java:2117)
at java.util.Scanner.nextInt(Scanner.java:2076)
at UnitClassSet.ContactUS.Raise_Funds_ContactUS_Form.SeriesOne_FillInContactUSForm(Raise_Funds_ContactUS_Form.java:34)
at UnitClassSet.ContactUS.test_ContactUS.ContactUSForms_Raise_Funds(test_ContactUS.java:11)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
... Removed 10 stack frames]]>
    </failure>
  </testcase> <!-- ContactUSForms_Raise_Funds -->
</testsuite> <!-- ContactUS forms -->
